Repository acm-ucr/aiatucr-website, pull requests merged in 2024-07, with the labels that each got.

#13 added information component
  package-lock.json
  package.json
  public/transparent_logo_1.webp
  src/components/landing/Information.jsx
Labels: Landing, Ready for Review, Changes Requested

#19 Kevinloritsch/Footer
  public/images/aitransparentlogo.png
  src/app/layout.js
  src/components/Footer.jsx
  tailwind.config.js
Labels: Ready for Review, General

#34 add tailwind colors
  tailwind.config.js
Labels: Ready for Review, General

#15 Implement Offerings
  src/app/page.js
  src/components/Footer.jsx
  src/components/landing/OfferingCard.js
  src/components/landing/OfferingCards.js
  tailwind.config.js
Labels: Landing, Ready for Review

#16 Implement Navigation
  public/logo.webp
  src/app/layout.js
  src/components/NavBar.jsx
  src/data/Navigation.js
  tailwind.config.js
Labels: Ready for Review, General

#25 Added headers
  package-lock.json
  public/wireframe.webp
  src/components/Header.jsx
Labels: General, Changes Requested

#32 implement upcoming event card
  src/Components/events/Card.jsx
Labels: Ready for Review, Events, Changes Requested

#42 Added Metadata to layout.js
  src/app/layout.js
Labels: Ready for Review, General

#43 updated readme file
  README.md
Labels: Ready for Review, General

#24 Agoel27/introduction component
  public/circuit.webp
  src/app/page.js
  src/components/landing/Introduction.jsx
Labels: Landing, Ready for Review

#47 Integrate components to landing page
  src/app/page.js
Labels: Landing, Ready for Review

#45 add board component #4
  images/342048951-0cf38a15-d725-4561-bffa-86adc7e21a16.png
  package-lock.json
  package.json
  public/images/board.webp
  src/Components/board/Board.jsx
  src/app/board/page.js
  tailwind.config.js
Labels: Board

#54 fix directory issue
  src/app/board/page.js
  src/components/board/Board.jsx
  src/components/events/Card.jsx
Labels: General
