Repository acm-ucr/aiatucr-website, pull requests merged in 2024-09, with the labels that each got.

#132 Fixed Board Page Mobile View
  src/components/board/Board.jsx
Labels: enhancement, Ready for Review

#130 Migrated Event
  src/app/layout.js
  src/components/calendar/Calendar.jsx
  src/components/calendar/CustomEvents.jsx
  src/components/calendar/CustomHeader.jsx
  src/components/calendar/CustomToolbar.jsx
  src/components/calendar/Modal.jsx
  src/components/calendar/index.css
  src/components/events/Card.jsx
  src/components/events/Event.jsx
  src/components/events/Events.jsx
  src/components/events/UpcomingEvents.jsx
Labels: Events

#131 Fixed footer icons new tab and spacing issue
  src/components/Footer.jsx
Labels: enhancement, Ready for Review

#135 final touches
  public/images/news-genie1.webp
  public/images/news-genie2.webp
  public/images/philip1.webp
  public/images/philip2.webp
  src/app/page.js
  src/app/projects/page.js
  src/components/calendar/Calendar.jsx
  src/components/calendar/CustomEvents.jsx
  src/components/calendar/CustomToolbar.jsx
  src/components/projects/ProjectCardLeft.jsx
  src/components/projects/ProjectCardRight.jsx
  src/data/Projects.js
Labels: General

#137 clean repository
  images/342048951-0cf38a15-d725-4561-bffa-86adc7e21a16.png
  images/meganyip.jpg
  public/board/board.webp
  public/board/christinekim.webp
  public/board/emilyho.webp
  public/board/freddysong.webp
  public/board/gregversteeg.webp
  public/board/johnnyz.webp
  public/board/meganyip.webp
  public/board/michaelchen.webp
  public/board/sazenshakya.webp
  public/landing/aitransparentlogo.webp
  public/landing/circuit.webp
  public/landing/transparent_logo_1.webp
  public/landing/wireframe.webp
  public/projects/news-genie1.webp
  public/projects/news-genie2.webp
  public/projects/philip1.webp
  public/projects/philip2.webp
  public/projects/projectCard.webp
  src/app/favicon.ico
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/board/Board.jsx
  src/components/landing/Information.jsx
  src/components/landing/Introduction.jsx
  src/components/projects/ProjectCardLeft.jsx
  src/components/projects/ProjectCardRight.jsx
  src/data/Board.js
  src/data/Projects.js
Labels: General
